export { BaseAdapter } from './adapters/base'
export { WebAdapter } from './adapters/web/index'
export { DesktopAdapter } from './adapters/desktop/index'
export { CapacitorAdapter } from './adapters/capacitor/index'
export { DBWrapper } from './db/wrapper'
export { SchemaRegistry } from './db/schema-registry'
export type { ColumnDef, TableSchema } from './db/schema-registry'
export { MigrationRunner } from './migrations/runner'
export { MigrationValidationError } from './migrations/validator'
export { SyncEngine } from './sync/engine'
export type { SyncEngineConfig } from './sync/engine'
export { OfflineWriteQueue } from './offline/write-queue'
export { ConflictResolver } from './conflict/resolver'
export { ConflictStore } from './conflict/store'
export { detectConflict } from './conflict/detector'
export { EncryptionManager } from './encryption/manager'
export { TokenManager } from './auth/token-manager'
export * from './types/index'
export { detectPlatform } from './utils/platform'
export { hlcNow, hlcRecv } from './utils/clock'
export { consoleLogger, noopLogger } from './utils/logger'
export type { Logger } from './utils/logger'
export { EventEmitter } from './utils/event-emitter'
